sslexceptions:
  - 'localhost'
  - '*.local'
flags:
  - 'enable-accelerated-mjpeg-decode'
  - 'enable-accelerated-video'
  - 'ignore-gpu-blacklist'
  - 'enable-native-gpu-memory-buffers'
  - 'enable-gpu-rasterization'
windows:
  - display: 0
    url: './index.html'
    title: 'OAK'
    background: '#ffffff'
    ontop: false
    insecure: false
    kiosk: false
    fullscreen: false
    frame: true
    size: '1024x500'
    x: 50
    y: 50
    node: true
    scripts:
      - 'hide-cursor.js'
  - display: 0
    url: './index.html'
    title: 'OAK'
    background: '#ffffff'
    ontop: false
    insecure: false
    kiosk: false
    fullscreen: false
    frame: true
    size: '1024x500'
    x: 100
    y: 100
    node: true
#    scripts:
#      - 'hide-cursor.js'