sslexceptions:
  - 'localhost'
  - '*.local'
domainwhitelist:
  - test.local
flags:
  ignore-gpu-blacklist:
    flag: 'ignore-gpu-blacklist'
  enable-native-gpu-memory-buffers:
    flag: 'enable-native-gpu-memory-buffers'
  enable-gpu-rasterization:
    flag: 'enable-gpu-rasterization'
shortcut:
  reload: false
  quit: false
server:
  host: 'localhost'
  port: 8000
waitforurls: true
extrawaitforurls:
  visit:
    url: 'https://visit.museum.wa.gov.au'
injectcss:
  simpleKeyboard:
    path: 'node_modules/simple-keyboard/build/css/index.css'
injectscripts:
  jquery:
    name: '$'
    path: 'node_modules/jquery/dist/jquery.min.js'
  simpleKeyboard:
    name: simpleKeyboard
    path: 'node_modules/simple-keyboard/build/index.js'
  simpleKeyboardLayouts:
    name: simpleKeyboardLayouts
    path: 'node_modules/simple-keyboard-layouts/build/index.js'
  keyboard:
    path: 'inject-scripts/keyboard.js'
windows:
  default:
    display: 0
    url: './index.html'
    title: 'Whistle Punk'
    background: '#ffffff'
    ontop: false
    insecure: false
    kiosk: false
    fullscreen: false
    frame: true
    width: 500
    height: 500
    x: 50
    y: 50
    node: true
    injectscripts:
      usejquery:
        path: 'inject-scripts/usejquery.js'