windows:
  - display: 1
    url: './index.html'
    title: 'OAK'
    background: '#ffffff'
    ontop: false
    insecure: false
    kiosk: false
    fullscreen: false
    frame: true
    size: '500x500'
    x: 50
    y: 50
    node: true
    flags:
      - 'ignore-gpu-blacklist'
#    scripts:
#      - '/home/andrew/projects/work/whistle-punk/hide-cursor.js'