windows:
  - display: 2
    url: './index.html'
    background: '#ffffff'
    ontop: false
    insecure: false
    kiosk: false
    fullscreen: false
    frame: true
    size: '500x500'
    x: 50
    y: 50
    flags:
      - '--ignore-gpu-blacklist'