windows:
  - display: 2
    url: './index.html'
    background: '#ffffff'
    ontop: false
    insecure: false
    kiosk: false
    fullscreen: false
    frame: true
#    scripts:
#  - display: 0
#    url: 'https://museum.wa.gov.au/'
#    background: '#ffffff'
#    ontop: false
#    insecure: false
#    kiosk: false
#    fullscreen: true